# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gtk2-Ex-DBITableFilter
version:      0.01
version_from: lib/Gtk2/Ex/DBITableFilter.pm
installdirs:  site
requires:
    Carp:                          0
    Data::Dumper:                  0
    DBD::CSV:                      0
    Glib:                          0
    Gtk2:                          0
    Gtk2::Ex::ComboBox:            0
    Gtk2::Ex::Simple::List:        0
    Gtk2::Ex::Threads::DBI:        0
    Gtk2::TestHelper:              0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
